# Dockerfile.bridge
FROM python:3.11

WORKDIR /app

RUN pip install --upgrade pip && \
    pip install --only-binary :all: eclipse-zenoh && \
    pip install kuksa-client requests

COPY kuksa_to_zenoh.py /app/kuksa_to_zenoh.py
COPY send_obd_data_to_kuksa.py /app/send_obd_data_to_kuksa.py

CMD ["python", "/app/kuksa_to_zenoh.py"]