# Dockerfile.adapter
FROM python:3.11

WORKDIR /app

RUN pip install --upgrade pip && \
    pip install --only-binary :all: eclipse-zenoh && \
    pip install requests

COPY ditto-adapter.py /app/ditto-adapter.py

CMD ["python", "/app/ditto-adapter.py"]